### ISSUE TITLE
Upgrade to metadata for multiple data sources of Metric and Log

### ISSUE THREAD

**Issue by jihyungSong** [cloudforet-io/monitoring#41]
Added a value called `supported_providers` to metadata to display monitoring and logs using multiple data sources for one cloud service resource.

For example,

```yaml
...
plugin_info:
  metadata:
    supported_providers:
    - aws
    - all
```

In the meantime, the `secret_data` passed to the DataSource used the `secret_id` obtained from the cloud service's collection_info, but now, if there is a `secret_id` in the metadata of the DataSource, it takes precedence.
